# Generated by Django 6.0 on 2026-01-29 10:09

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.CharField(help_text='Relative path to product image', max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('rating_stars', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('price_cents', models.PositiveIntegerField(help_text='Price in cents (e.g., 3800 = $38.00)')),
                ('keywords', models.JSONField(default=list, help_text='List of keywords/tags for the product')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
