# Generated by Django 6.0 on 2026-02-04 14:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_cents', models.ImageField(default=0, upload_to='')),
                ('delivery_days', models.ImageField(default=7, upload_to='')),
            ],
        ),
    ]
