# Generated by Django 6.0 on 2026-02-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoptions',
            name='delivery_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='deliveryoptions',
            name='price_cents',
            field=models.IntegerField(default=0),
        ),
    ]
